### PR TITLE
prevent variable-sized object initialization

### PR DESCRIPTION
**Pull request by Karsten1987**
Clang/OSX won't compile a variable-sized c-style array initialization.

```
[ 88%] Building CXX object CMakeFiles/test_controller_with_options.dir/test/test_controller_with_options.cpp.o
/Users/karsten/workspace/ros2/ros2_control_ws/src/ros-controls/ros2_control/controller_interface/test/test_controller_with_options.cpp:29:27: error: variable-sized object may not be initialized
  char const * const argv[argc] = {"", "--ros-args", "-p", "parameter_list.parameter1:=1.", "-p",
                          ^~~~
/Users/karsten/workspace/ros2/ros2_control_ws/src/ros-controls/ros2_control/controller_interface/test/test_controller_with_options.cpp:50:27: error: variable-sized object may not be initialized
  char const * const argv[argc] = {""};
                          ^~~~
2 errors generated.
```

Error was introduced in #382

### CODE REVIEW

File: controller_interface/test/test_controller_with_options.cpp [hunk 1]
```diff
@@ -26,7 +26,7 @@ class FriendControllerWithOptions : public controller_with_options::ControllerWi
 TEST(ControllerWithOption, init_with_overrides) {
   // mocks the declaration of overrides parameters in a yaml file
   int argc = 8;
-  char const * const argv[argc] = {"", "--ros-args", "-p", "parameter_list.parameter1:=1.", "-p",
+  char const * const argv[8] = {"", "--ros-args", "-p", "parameter_list.parameter1:=1.", "-p",
```
Comment (matthew-reynolds) [inline controller_interface/test/test_controller_with_options.cpp:29]: How about using a constexpr to avoid duplicating the magic number:

```
constexpr int argc = 8;
char const * const argv[argc] = {"", "--ros-args", "-p", ... };
rclcpp::init(arrlen(argv), argv);
```

Or better yet, just infer the length from the initializer list:
```
template<class T, size_t N>
constexpr size_t arrlen(T (&)[N]) { return N; }

...

char const * const argv[] = {"", "--ros-args", "-p", ... };
rclcpp::init(arrlen(argv), argv);
```

Comment (Karsten1987) [reply controller_interface/test/test_controller_with_options.cpp]: Very much like that solution. I was just being lazy :P

**Review by matthew-reynolds — APPROVED** [review]
